export const products = [
  {
    id: 1,
    title: "Giordano",
    description: "Men's Denim Solid Casual Shirt",
    price: 899,
    rating: 4.09,
    category: "Clothes",
    thumbnail:
      "https://images.unsplash.com/photo-1516257984-b1b4d707412e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWVucyUyMGZhc2hpb258ZW58MHx8MHx8fDA%3D&w=1000&q=80",
  },
  {
    id: 2,
    title: "Centrino",
    description: "Men's Casual Shoes",
    price: 1599,
    rating: 4.03,
    category: "Shoes",
    thumbnail:
      "https://www.jiomart.com/images/product/original/rvcmtnb9mf/zixer-streetwear-pro-style-high-top-platform-fashion-sneakers-sports-casual-shoes-for-men-ankle-casual-shoes-for-men-latest-boots-for-men-dancing-shoes-product-images-rvcmtnb9mf-0-202303281522.jpg?im=Resize=(330,410)",
  },
  {
    id: 3,
    title: "  REDUX",
    description: "RWS0220S Analogue Blue Dial Men's & Boy's Watch",
    price: 1999,
    rating: 4.0,
    category: "Watch",
    thumbnail:
      "https://i.pinimg.com/originals/2a/35/7a/2a357ab61467e42e4f0bbc12962989ca.jpg",
  },
  {
    id: 4,
    title: "TRAWOC ",
    description: "Backpack Hiking Trekking Bag Rucksack",
    price: 2999,
    rating: 4.02,
    category: "Backpack",
    thumbnail:
      "https://images.squarespace-cdn.com/content/v1/6010e9a73157c846a7108cbd/904a75af-cca1-4b01-ac4b-20f54b77f73c/2022_Baseline_Composite_2.jpg",
  },
  {
    id: 5,
    title: "VINCENT CHASE",
    description: "Full Rim Round Branded Latest and Stylish Sunglasses",
    price: 999,
    rating: 4.01,
    category: "Sunglasses",
    thumbnail:
      "https://sunniesstudios.com/cdn/shop/products/WhiteGoldPondFull_ValFront.jpg?v=1684985131",
  },
  {
    id: 6,
    title: "RARE",
    description: "Women's Synthetic a-line Knee-Long Dress",
    price: 599,
    rating: 4.05,
    category: "Clothes",
    thumbnail:
      "https://assets.myntassets.com/dpr_1.5,q_60,w_400,c_limit,fl_progressive/assets/images/22120556/2023/2/25/986d6f97-fe9b-487a-9c64-f577e0a32c491677314970316KhushalKwomenEmbroideryKurtaandpalazzowithdupattaset7.jpg",
  },
  {
    id: 7,
    title: "PARAGON",
    description: "Giordano K6017L Women Sandals  Casual & Formal Sandals",
    price: 499,
    rating: 3.9,
    category: "Sandals",
    thumbnail:
      "https://www.libertyshoesonline.com/pub/media/catalog/product/cache/d27f3f74a53679e84179ee8edfe784ba/g/i/gi-bz-l6_blue_1_1.jpg",
  },
  {
    id: 8,
    title: "Giordano",
    description: "Analog Rose Gold Dial Women's Watch-BQ3181",
    price: 2999,
    rating: 4.05,
    category: "Watch",
    thumbnail:
      "https://sc04.alicdn.com/kf/Hca7c5489d4d24da38966045347a63b32Q.jpg",
  },
  {
    id: 9,
    title: "Sukkhi",
    description: "Modish Gold Plated Necklace  Set for Women",
    price: 1599,
    rating: 4.05,
    category: "Jewellery",
    thumbnail:
      "https://platinumevara.com/wp-content/uploads/2023/02/1-74-5-1.webp",
  },
  {
    id: 10,
    title: "FEISEDY",
    description: "Women Cateye Sunglasses With UV400 HD Lens",
    price: 899,
    rating: 3.05,
    category: "Sunglasses",
    thumbnail:
      "https://image-cdn.trenbe.com/productmain-image/20230305_638135684458561747_16771021_0.jpg",
  },
  {
    id: 11,
    title: "Generic",
    description: "S N Collection Casual Solid  Jumpsuit Dress for Girls",
    price: 1299,
    rating: 4.0,
    category: "Clothes",
    thumbnail:
      "https://cdn.media.amplience.net/i/mrpricegroup/01_101972204_SI_00?$preset$&w=320",
  },
  {
    id: 12,
    title: "Skechers",
    description: "Boys Snap Sprints 2.0 Sneaker",
    price: 599,
    rating: 4.09,
    category: "Clothes",
    thumbnail:
      "https://5.imimg.com/data5/PW/DS/GT/SELLER-65814696/kids-shoes.jpg",
  },
];

// export const products = [
//   {
//     id: 1,
//     title: "iPhone 9",
//     description: "An apple mobile which is nothing like apple",
//     price: 549,
//     discountPercentage: 12.96,
//     rating: 4.69,
//     stock: 94,
//     brand: "Apple",
//     category: "smartphones",
//     thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
//     images: [
//       "https://i.dummyjson.com/data/products/1/1.jpg",
//       "https://i.dummyjson.com/data/products/1/2.jpg",
//       "https://i.dummyjson.com/data/products/1/3.jpg",
//       "https://i.dummyjson.com/data/products/1/4.jpg",
//       "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
//     ],
//   },
//   {
//     id: 2,
//     title: "iPhone X",
//     description:
//       "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
//     price: 899,
//     discountPercentage: 17.94,
//     rating: 4.44,
//     stock: 34,
//     brand: "Apple",
//     category: "smartphones",
//     thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
//     images: [
//       "https://i.dummyjson.com/data/products/2/1.jpg",
//       "https://i.dummyjson.com/data/products/2/2.jpg",
//       "https://i.dummyjson.com/data/products/2/3.jpg",
//       "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
//     ],
//   },
//   {
//     id: 3,
//     title: "Samsung Universe 9",
//     description:
//       "Samsung's new variant which goes beyond Galaxy to the Universe",
//     price: 1249,
//     discountPercentage: 15.46,
//     rating: 4.09,
//     stock: 36,
//     brand: "Samsung",
//     category: "smartphones",
//     thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
//     images: ["https://i.dummyjson.com/data/products/3/1.jpg"],
//   },
//   {
//     id: 4,
//     title: "OPPOF19",
//     description: "OPPO F19 is officially announced on April 2021.",
//     price: 280,
//     discountPercentage: 17.91,
//     rating: 4.3,
//     stock: 123,
//     brand: "OPPO",
//     category: "smartphones",
//     thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
//     images: [
//       "https://i.dummyjson.com/data/products/4/1.jpg",
//       "https://i.dummyjson.com/data/products/4/2.jpg",
//       "https://i.dummyjson.com/data/products/4/3.jpg",
//       "https://i.dummyjson.com/data/products/4/4.jpg",
//       "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
//     ],
//   },
//   {
//     id: 5,
//     title: "Huawei P30",
//     description:
//       "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
//     price: 499,
//     discountPercentage: 10.58,
//     rating: 4.09,
//     stock: 32,
//     brand: "Huawei",
//     category: "smartphones",
//     thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
//     images: [
//       "https://i.dummyjson.com/data/products/5/1.jpg",
//       "https://i.dummyjson.com/data/products/5/2.jpg",
//       "https://i.dummyjson.com/data/products/5/3.jpg",
//     ],
//   },
// ];
